spring:
  application:
    name: recommendation-signature-server
server:
  port: 8080

model:
  url: http://ml_service
  url-to-predict: ${model.url}/predict
  url-to-predict-with-context: ${model.url}/predictwithcontext

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  prometheus:
    metrics:
      export:
        enabled: true