spring:
  application:
    name: recommendation-signature-server
  datasource:
    url: jdbc:h2:mem:recommendationDB
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
server:
  port: 8080

model:
  url: http://ml_service
  url-to-predict: ${model.url}/predict
  url-to-predict-with-context: ${model.url}/predict-with-context

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  prometheus:
    metrics:
      export:
        enabled: true